version: '3.2'
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - '4566:4566'
    environment:
      - LOCALSTACK_SERVICES=s3
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'